name: Smart Contract PR Reviewer

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.sol'

permissions:
  contents: read
  pull-requests: write

jobs:
  smart-contract-pr-reviewer:
    runs-on: ubuntu-latest

    env:
      BACKEND_URL: ${{ secrets.BACKEND_URL }}

    steps:
      - name: Smart Contract PR Reviewer
        uses: nisarg-shah-222/smart-contract-pr-reviewer@v1.1
        with:
          backend_url: ${{ env.BACKEND_URL }}